version: "2"
services:
  web:
    build:
        context: .
    image: registry.cn-hangzhou.aliyuncs.com/jingshan/bootkeycloak:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      - KEYCLOAK_AUTH_SERVER_URL=http://<keycloak server address>:<port>/auth